import { DialogBody, DialogButton, DialogControlsSection, DialogControlsSectionHeader, Field, Navigation } from "@decky/ui";
import { ExternalAppsPurgeButton, ExternalAppsSyncButton, LabelWithIcon, ToggleField } from "../shared";
import { FC, ReactNode, useContext } from "react";
import { useCurrentHostSettings, useCurrentSettings, useNonSteamAppShortcuts } from "../../hooks";
import { AppType } from "../../lib";
import { HostOff } from "../icons";
import { MoonDeckContext } from "../../contexts";

export const NonSteamAppsView: FC = () => {
  const { settingsManager } = useContext(MoonDeckContext);
  const settings = useCurrentSettings();
  const hostSettings = useCurrentHostSettings();
  const shortcuts = useNonSteamAppShortcuts();

  let syncButton: ReactNode = null;
  if (settings == null || hostSettings === null) {
    syncButton =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Sync with Buddy</DialogControlsSectionHeader>
        <Field
          label={<LabelWithIcon icon={HostOff} label="HOST IS NOT SELECTED" />}
          description="Go to host selection page to select host"
          bottomSeparator="none" />
      </DialogControlsSection>;
  } else {
    syncButton =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Sync with Buddy</DialogControlsSectionHeader>
        <Field
          label="Sync all Non-Steam apps via Buddy"
          description="Steam client will be started on the running host if needed and the SteamDeck client might be restarted afterwards!"
          childrenContainerWidth="fixed"
        >
          <ExternalAppsSyncButton text="Sync Apps" appType={AppType.NonSteam} />
        </Field>
        <ToggleField
          label="Show button in Quick Access Menu"
          description="Confirmation dialog will not be displayed when using it!"
          value={hostSettings.nonSteamApps.showQuickAccessButton}
          setValue={(value) => settingsManager.updateHost((settings) => { settings.nonSteamApps.showQuickAccessButton = value; })}
        />
      </DialogControlsSection>;
  }

  let shortcutsList: ReactNode = null;
  if (shortcuts.length > 0) {
    shortcutsList =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Generated Shortcuts</DialogControlsSectionHeader>
        {shortcuts.map((shortcut) => {
          return (
            <Field
              key={shortcut.appId}
              label={shortcut.appName}
              childrenContainerWidth="min"
            >
              <DialogButton onClick={() => Navigation.Navigate(`/library/app/${shortcut.appId}`)}>
                Open
              </DialogButton>
            </Field>
          );
        })}
      </DialogControlsSection>;
  }

  return (
    <DialogBody>
      <DialogControlsSection>
        <DialogControlsSectionHeader>What are the Non-Steam Apps?</DialogControlsSectionHeader>
        <Field
          description={
            <>
              <div>These are the non-Steam shortcuts generated by MoonDeck from the shortcuts.vdf file on host.</div>
              <div>Buddy needs to be configured to access the app list, otherwise this feature will not work!</div>
              <br />
              <div>MoonDeck will try to preserve shortcuts if their name or executable does not change. This should keep any custom artwork added to the shortcuts.</div>
              <div>If this cannot be done, the shortcuts will be removed and new ones created.</div>
            </>
          }
          focusable={true}
        />
      </DialogControlsSection>
      <DialogControlsSection>
        <DialogControlsSectionHeader>Cleanup</DialogControlsSectionHeader>
        <Field
          label="Purge all generated shortcuts!"
          description="Steam client might be restarted afterwards!"
          childrenContainerWidth="fixed"
        >
          <ExternalAppsPurgeButton disabled={shortcuts.length === 0} appType={AppType.NonSteam} />
        </Field>
      </DialogControlsSection>
      {syncButton}
      {shortcutsList}
    </DialogBody>
  );
};
