import { AppDetails, DialogBody, DialogButton, DialogControlsSection, DialogControlsSectionHeader, Field, Navigation } from "decky-frontend-lib";
import { BuddyProxy, SettingsManager, getAllExternalAppDetails, logger } from "../../lib";
import { ReactNode, VFC, useEffect, useState } from "react";
import { HostOff } from "../icons";
import { LabelWithIcon } from "../shared";
import { PurgeButton } from "./purgebutton";
import { SyncButton } from "./syncbutton";
import { useCurrentHostSettings } from "../../hooks";

interface Props {
  settingsManager: SettingsManager;
  buddyProxy: BuddyProxy;
}

export const SunshineAppsView: VFC<Props> = ({ settingsManager, buddyProxy }) => {
  const hostSettings = useCurrentHostSettings(settingsManager);
  const [shortcuts, setShortcuts] = useState<AppDetails[]>([]);

  const refreshApps = (): void => {
    (async () => {
      let data = await getAllExternalAppDetails();
      data = data.sort((a, b) => a.strDisplayName < b.strDisplayName ? -1 : a.strDisplayName > b.strDisplayName ? 1 : 0);
      setShortcuts(data);
    })().catch((e) => logger.critical(e));
  };

  useEffect(refreshApps, []);

  let syncButton: ReactNode = null;
  if (hostSettings === null) {
    syncButton =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Sync with Buddy</DialogControlsSectionHeader>
        <Field
          label={<LabelWithIcon icon={HostOff} label="HOST IS NOT SELECTED" />}
          description="Go to host selection page to select host"
          bottomSeparator="none" />
      </DialogControlsSection>;
  } else {
    syncButton =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Sync with Buddy</DialogControlsSectionHeader>
        <Field
          label="Sync all Sunshine's apps via Buddy"
          description="Steam client might be restarted afterwards!"
          childrenContainerWidth="fixed"
        >
          <SyncButton shortcuts={shortcuts} moonDeckHostApps={hostSettings.hostApp.apps} hostName={hostSettings.hostName} buddyProxy={buddyProxy} refreshApps={refreshApps} />
        </Field>
      </DialogControlsSection>;
  }

  let shortcutsList: ReactNode = null;
  if (shortcuts.length > 0) {
    shortcutsList =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Generated Shortcuts</DialogControlsSectionHeader>
        {shortcuts.map((shortcut) => {
          return (
            <Field
              key={shortcut.unAppID}
              label={shortcut.strDisplayName}
              childrenContainerWidth="min"
            >
              <DialogButton onClick={() => Navigation.Navigate(`/library/app/${shortcut.unAppID}`)}>
                Open
              </DialogButton>
            </Field>
          );
        })}
      </DialogControlsSection>;
  }

  return (
    <DialogBody>
      <DialogControlsSection>
        <DialogControlsSectionHeader>What are the Sunshine Apps?</DialogControlsSectionHeader>
        <Field
          description={
            <>
              <div>These are the non-Steam shortcuts generated by MoonDeck from Sunshine's app list.</div>
              <div>Buddy needs to be configured to access the app list, otherwise this feature will not work!</div>
              <br />
              <div>Sunshine apps will not be supported by MoonDeck in any way apart from manually syncing them.</div>
              <div>This means no automatic resolution change or anything else!</div>
              <br />
              <div>These shortcuts are host-sensitive - if you change the hostname, they might no longer work!</div>
              <div>In this case you can re-sync. If the names do not change, only the launch options will be updated and artwork will remain.</div>
            </>
          }
          focusable={true}
        />
      </DialogControlsSection>
      <DialogControlsSection>
        <DialogControlsSectionHeader>Cleanup</DialogControlsSectionHeader>
        <Field
          label="Purge all generated shortcuts!"
          description="Steam client might be restarted afterwards!"
          childrenContainerWidth="fixed"
        >
          <PurgeButton shortcuts={shortcuts} />
        </Field>
      </DialogControlsSection>
      {syncButton}
      {shortcutsList}
    </DialogBody>
  );
};
