import { AppDetails, DialogBody, DialogButton, DialogControlsSection, DialogControlsSectionHeader, Field, Navigation } from "@decky/ui";
import { BuddyProxy, SettingsManager, getAllGameStreamAppDetails, logger } from "../../lib";
import { FC, ReactNode, useEffect, useState } from "react";
import { LabelWithIcon, SunshineAppsSyncButton, ToggleField } from "../shared";
import { useCurrentHostSettings, useCurrentSettings } from "../../hooks";
import { HostOff } from "../icons";
import { PurgeButton } from "./purgebutton";

interface Props {
  settingsManager: SettingsManager;
  buddyProxy: BuddyProxy;
}

export const SunshineAppsView: FC<Props> = ({ settingsManager, buddyProxy }) => {
  const settings = useCurrentSettings(settingsManager);
  const hostSettings = useCurrentHostSettings(settingsManager);
  const [shortcuts, setShortcuts] = useState<AppDetails[]>([]);

  const refreshApps = (): void => {
    (async () => {
      let data = await getAllGameStreamAppDetails();
      data = data.sort((a, b) => a.strDisplayName < b.strDisplayName ? -1 : a.strDisplayName > b.strDisplayName ? 1 : 0);
      setShortcuts(data);
    })().catch((e) => logger.critical(e));
  };

  useEffect(refreshApps, []);

  let syncButton: ReactNode = null;
  if (settings == null || hostSettings === null) {
    syncButton =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Sync with Buddy</DialogControlsSectionHeader>
        <Field
          label={<LabelWithIcon icon={HostOff} label="HOST IS NOT SELECTED" />}
          description="Go to host selection page to select host"
          bottomSeparator="none" />
      </DialogControlsSection>;
  } else {
    syncButton =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Sync with Buddy</DialogControlsSectionHeader>
        <Field
          label="Sync all Sunshine's apps via Buddy"
          description="Steam client might be restarted afterwards!"
          childrenContainerWidth="fixed"
        >
          <SunshineAppsSyncButton shortcuts={shortcuts} buddyProxy={buddyProxy} hostSettings={hostSettings} refreshApps={refreshApps} />
        </Field>
        <ToggleField
          label="Show button in Quick Access Menu"
          description="Confirmation dialog will not be displayed when using it!"
          value={hostSettings.sunshineApps.showQuickAccessButton}
          setValue={(value) => settingsManager.updateHost((settings) => { settings.sunshineApps.showQuickAccessButton = value; })}
        />
      </DialogControlsSection>;
  }

  let shortcutsList: ReactNode = null;
  if (shortcuts.length > 0) {
    shortcutsList =
      <DialogControlsSection>
        <DialogControlsSectionHeader>Generated Shortcuts</DialogControlsSectionHeader>
        {shortcuts.map((shortcut) => {
          return (
            <Field
              key={shortcut.unAppID}
              label={shortcut.strDisplayName}
              childrenContainerWidth="min"
            >
              <DialogButton onClick={() => Navigation.Navigate(`/library/app/${shortcut.unAppID}`)}>
                Open
              </DialogButton>
            </Field>
          );
        })}
      </DialogControlsSection>;
  }

  return (
    <DialogBody>
      <DialogControlsSection>
        <DialogControlsSectionHeader>What are the Sunshine Apps?</DialogControlsSectionHeader>
        <Field
          description={
            <>
              <div>These are the non-Steam shortcuts generated by MoonDeck from Sunshine's app list.</div>
              <div>Buddy needs to be configured to access the app list, otherwise this feature will not work!</div>
              <br />
              <div>Sunshine apps support almost all of the usual MoonDeck app features, except closing Steam on host on stream end and changing the app name to AppId.</div>
              <br />
              <div>These shortcuts are host-sensitive - if you change the hostname, they might no longer work!</div>
              <div>In this case you can re-sync. If the names do not change, only the launch options will be updated and artwork will remain.</div>
            </>
          }
          focusable={true}
        />
      </DialogControlsSection>
      <DialogControlsSection>
        <DialogControlsSectionHeader>Cleanup</DialogControlsSectionHeader>
        <Field
          label="Purge all generated shortcuts!"
          description="Steam client might be restarted afterwards!"
          childrenContainerWidth="fixed"
        >
          <PurgeButton shortcuts={shortcuts} />
        </Field>
      </DialogControlsSection>
      {syncButton}
      {shortcutsList}
    </DialogBody>
  );
};
